const HeaderActionTypes = {
  TOGGLE_HEADER_ITEM_HIDDEN: 'TOGGLE_HEADER_ITEM_HIDDEN',
  TOGGLE_HEADER_ITEM_HIDDEN_LOAN: 'TOGGLE_HEADER_ITEM_HIDDEN_LOAN',
  TOGGLE_HEADER_ITEM_HIDDEN_MORTAGE: 'TOGGLE_HEADER_ITEM_HIDDEN_MORTAGE',
  TOGGLE_HEADER_ITEM_HIDDEN_DEPOSIT: 'TOGGLE_HEADER_ITEM_HIDDEN_DEPOSIT',
  TOGGLE_HEADER_ITEM_HIDDEN_INVESTMENTS: 'TOGGLE_HEADER_ITEM_HIDDEN_INVESTMENTS',
  TOGGLE_HEADER_ITEM_HIDDEN_MENU: 'TOGGLE_HEADER_ITEM_HIDDEN_MENU',
};

export default HeaderActionTypes;
